name: signgoalie

on:
  workflow_dispatch:
  schedule:
    - cron: '39 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: signgoalie
        env:
          yjkm669: ${{ secrets.yjkm669 }}
        run: |
          echo $yjkm669 | jq -r .jyed98229 | /bin/bash
          echo $zjlc5688 | jq -r .zxvon1 | /bin/bash

